#!/bin/sh

exec 2>&1

export PCSC_READER_PATTERN="Contactless"
export TUERD_REPO_PATH="/home/clubmonitor/git"
export USBLOCKD_PIDFILE="/var/run/usblockd.pid"

export LIBMF_DEBUG=0
export TUERD_DEBUG=0

echo $$ > /var/run/tuerd.pid

exec chpst -utuerd:tuerd /usr/local/sbin/tuerd
